// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/assets": {
            "get": {
                "description": "Get a paginated list of assets",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "List assets",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int32",
                        "description": "Number of items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Pagination cursor for next page",
                        "name": "cursor",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_core_response.BaseResponse-array_github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_res_AssetPreviewRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_core_response.BaseResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_core_response.BaseResponse-any"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new asset with name, price, product URL and image count",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "Create a new asset",
                "parameters": [
                    {
                        "description": "Create asset request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_req.CreateAssetReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_core_response.BaseResponse-github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_res_CreateAssetRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_core_response.BaseResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_core_response.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/assets/import": {
            "post": {
                "description": "Create an asset with IMPORTING status and a SCRAPE_PRODUCT job",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "Import asset from product URL",
                "parameters": [
                    {
                        "description": "Import asset request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_req.ImportAssetReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_core_response.BaseResponse-github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_res_ImportAssetRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_core_response.BaseResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_core_response.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/assets/{id}": {
            "get": {
                "description": "Retrieve detailed information about a specific asset",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "Get asset by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Asset ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_core_response.BaseResponse-github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_res_AssetRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_core_response.BaseResponse-any"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_core_response.BaseResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_core_response.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/assets/{id}/confirm": {
            "post": {
                "description": "Confirm upload for an asset and generate image URLs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "Confirm asset upload",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Asset ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_core_response.BaseResponse-github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_res_ConfirmAssetRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_core_response.BaseResponse-any"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_core_response.BaseResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_core_response.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/assets/{id}/images/upload-url": {
            "get": {
                "description": "Generate a presigned URL for uploading an image to an asset",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "Get image upload URL",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Asset ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "File name",
                        "name": "fileName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_core_response.BaseResponse-github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_res_AssetUpload"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_core_response.BaseResponse-any"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_core_response.BaseResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_core_response.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/assets/{id}/images/{imageId}": {
            "delete": {
                "description": "Delete an image from an asset",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "Delete asset image",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Asset ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Image ID",
                        "name": "imageId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_core_response.BaseResponse-any"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_core_response.BaseResponse-any"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_core_response.BaseResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_core_response.BaseResponse-any"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_gianghp123_Vidmerce_backend_internal_core_response.BaseResponse-any": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {},
                "meta": {
                    "description": "optional",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_core_response.Meta"
                        }
                    ]
                }
            }
        },
        "github_com_gianghp123_Vidmerce_backend_internal_core_response.BaseResponse-array_github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_res_AssetPreviewRes": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_res.AssetPreviewRes"
                    }
                },
                "error": {},
                "meta": {
                    "description": "optional",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_core_response.Meta"
                        }
                    ]
                }
            }
        },
        "github_com_gianghp123_Vidmerce_backend_internal_core_response.BaseResponse-github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_res_AssetRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_res.AssetRes"
                },
                "error": {},
                "meta": {
                    "description": "optional",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_core_response.Meta"
                        }
                    ]
                }
            }
        },
        "github_com_gianghp123_Vidmerce_backend_internal_core_response.BaseResponse-github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_res_AssetUpload": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_res.AssetUpload"
                },
                "error": {},
                "meta": {
                    "description": "optional",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_core_response.Meta"
                        }
                    ]
                }
            }
        },
        "github_com_gianghp123_Vidmerce_backend_internal_core_response.BaseResponse-github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_res_ConfirmAssetRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_res.ConfirmAssetRes"
                },
                "error": {},
                "meta": {
                    "description": "optional",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_core_response.Meta"
                        }
                    ]
                }
            }
        },
        "github_com_gianghp123_Vidmerce_backend_internal_core_response.BaseResponse-github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_res_CreateAssetRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_res.CreateAssetRes"
                },
                "error": {},
                "meta": {
                    "description": "optional",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_core_response.Meta"
                        }
                    ]
                }
            }
        },
        "github_com_gianghp123_Vidmerce_backend_internal_core_response.BaseResponse-github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_res_ImportAssetRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_res.ImportAssetRes"
                },
                "error": {},
                "meta": {
                    "description": "optional",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_core_response.Meta"
                        }
                    ]
                }
            }
        },
        "github_com_gianghp123_Vidmerce_backend_internal_core_response.Meta": {
            "type": "object",
            "properties": {
                "has_more": {
                    "type": "boolean"
                },
                "last_key": {
                    "description": "Cursor-style (DynamoDB, etc.)"
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "description": "SQL-style pagination",
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_req.CreateAssetReq": {
            "type": "object",
            "required": [
                "name",
                "price",
                "productUrl"
            ],
            "properties": {
                "imageCount": {
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 1,
                    "example": 3
                },
                "name": {
                    "type": "string",
                    "example": "iPhone 15"
                },
                "price": {
                    "type": "number",
                    "example": 999.99
                },
                "productUrl": {
                    "type": "string",
                    "example": "https://example.com/products/iphone-15"
                }
            }
        },
        "github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_req.ImportAssetReq": {
            "type": "object",
            "required": [
                "productUrl"
            ],
            "properties": {
                "productUrl": {
                    "type": "string",
                    "example": "https://..."
                }
            }
        },
        "github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_res.AssetPreviewRes": {
            "type": "object",
            "properties": {
                "assetId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "image": {
                    "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_res.ImageInfo"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "productUrl": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_res.AssetRes": {
            "type": "object",
            "properties": {
                "assetId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_res.ImageInfo"
                    }
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "productUrl": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_res.AssetUpload": {
            "type": "object",
            "properties": {
                "expiresIn": {
                    "type": "integer",
                    "example": 300
                },
                "fileKey": {
                    "type": "string",
                    "example": "assets/abc123/1.jpg"
                },
                "uploadUrl": {
                    "type": "string",
                    "example": "https://s3.amazonaws.com/bucket/asset-url"
                }
            }
        },
        "github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_res.ConfirmAssetRes": {
            "type": "object",
            "properties": {
                "assetId": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_res.ImageInfo"
                    }
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_res.CreateAssetRes": {
            "type": "object",
            "properties": {
                "assetId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "uploads": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_res.UploadInfo"
                    }
                }
            }
        },
        "github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_res.ImageInfo": {
            "type": "object",
            "properties": {
                "imageId": {
                    "type": "string"
                },
                "imageUrl": {
                    "type": "string"
                },
                "order": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_res.ImportAssetRes": {
            "type": "object",
            "properties": {
                "assetId": {
                    "type": "string"
                },
                "jobId": {
                    "type": "string"
                }
            }
        },
        "github_com_gianghp123_Vidmerce_backend_internal_modules_assets_dtos_res.UploadInfo": {
            "type": "object",
            "properties": {
                "expiresIn": {
                    "type": "integer"
                },
                "fileKey": {
                    "type": "string"
                },
                "order": {
                    "type": "integer"
                },
                "uploadUrl": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "Swagger Assets API",
	Description:      "This is the Vidmerce Assets API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
