routes:
  assets_root:
    path: /api/assets
    lambda_key: assets
  assets:
    path: /api/assets/{proxy+}
    lambda_key: assets
  webhooks:
    path: /api/webhooks/{proxy+}
    lambda_key: webhooks

