lambda_functions:
  assets:
    function_name: assets_lambda
    handler: bootstrap
    filename: artifacts/lambdas/assets/function.zip
    runtime: provided.al2023
    s3_bucket_key: asset-storage
    db_table_key: MediaProjectTable
  webhooks:
    function_name: webhooks_lambda
    handler: bootstrap
    filename: artifacts/lambdas/webhooks/function.zip
    runtime: provided.al2023