lambda_functions:
  assets:
    function_name: assets_lambda
    handler: bootstrap
    filename: functions/cmd/assets/function.zip
    runtime: provided.al2023
  videos:
    function_name: videos_lambda
    handler: bootstrap
    filename: functions/cmd/videos/function.zip
    runtime: provided.al2023
  