lambda_functions:
  assets:
    function_name: assets_lambda
    handler: bootstrap
    filename: artifacts/lambdas/assets/function.zip
    runtime: provided.al2023
    s3_bucket_key: asset-storage
    db_table_key: MediaProjectTable
  videos:
    function_name: videos_lambda
    handler: bootstrap
    filename: artifacts/lambdas/videos/function.zip
    runtime: provided.al2023
    s3_bucket_key: asset-storage
    db_table_key: MediaProjectTable